name: ssdg
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.10.13
    - numpy
    - pandas
    - opencv
    - pytorch
    - torchvision
    - scikit-learn
    - matplotlib