name: ssdg2
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - numpy
    - pandas
    - pytorch=0.4
    - torchvision=0.2
    - scikit-learn
    - matplotlib